export const LOADING_APPOINTMENTS = "LOADING_APPOINTMENTS";
export const LOADED_APPOINTMENTS = "LOADED_APPOINTMENTS";

export const FILTER_NAME = "FILTER_NAME";

export const FILTER_TYPE = "FILTER_TYPE";

export const FILTER_DATE = "FILTER_DATE";

export const FILTER_PATIENTS = "FILTER_PATIENTS";

export const UPDATE_BUBBLE = "UPDATE_BUBBLE";
